version: "3.9"
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "backend"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    env_file:
      - ./env/backend.env
    depends_on:
      - "psql"
  psql:
    image: "postgres"
    ports:
      - "5432"
    volumes:
      - sdc:/var/lib/postgresql/data
    env_file:
      - ./env/psql.env
volumes:
  sdc: